name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn install
        yarn run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        terraform_plan_json: |
          {
            "resource_changes": [
              {
                "address": "module.app.module.database.aws_db_instance.database",
                "type": "aws_db_instance",
                "name": "database",
                "change": {
                  "actions": ["delete"]
                }
              },
              {
                "address": "module.app.aws_security_group_rule.db_access",
                "type": "aws_security_group_rule",
                "name": "db_access",
                "change": {
                  "actions": ["delete", "create"]
                }
              }
            ]
          }